### ISSUE TITLE
TODO global

### ISSUE THREAD

**Issue by YuryLobkov** [YuryLobkov/cooktail#11]
### Major issues
- [x] comments feature
- [x] paging all list views
- [x] #15
- [x] #12
- [x] Sort posts from new to old
- [x] Custom 404 page
- [ ] Check for security issues
- [x] #20
- [ ] Footer content (contact us, social e.t.c.)
- [x] #23 
### Minor issues
- [x] fav.ico and document name

### Future ideas

1. Photo compressor and watermarker
2. Use slugs instead of ID`s
3. Add filters to cocktails list
4. View CreateCocktail: devide CheckboxMultipleSelect`s by groups (ex. Tableware, Tools, etc.)
5. View Mystorage/tools: devide tags by groups
